language: go

go:
  - 1.7

install:
  - go get github.com/tools/godep
  - godep restore
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -cover -failOnPending
  - go build ./...
  - ./publish.sh
